### ISSUE TITLE
You can render through blocks by using mechanical spawner

### ISSUE THREAD

**Issue by liangmoe** [oierbravo/create-mechanical-spawner#14]
### Describe the Bug

Not sure why but you can x-raying by placing mechanical spawner

### Reproduction Steps

1. obtain mechanical spawner
2. place it on the ground and nearby blocks
3. X-ray
...

### Expected Result

X-raying should not happened?

### Screenshots and Videos

![2024-04-29_17 42 11](https://github.com/oierbravo/create-mechanical-spawner/assets/135343248/b3439f75-15d0-49c9-8499-fae98e794c86)

### Crash Report or Log

https://mclo.gs/ySF74Zv

### Operating System

Windows 10

### Mod Version

0.0.9.c-36

### Minecraft Version

1.19.2

### Forge Version

47.1.3

### Other Mods

modernfix, ferritcore

### Additional Context

My minecraft version is 1.20.1 and the mod version is 0.0.14.e-22

**Comment by wolfieboy09** [comment]
I know how to fix this, I will open a PR with it
