### ISSUE TITLE
Buckets are missing recipe

### ISSUE THREAD

**Issue by wolfieboy09** [oierbravo/create-mechanical-spawner#16]
### Describe the Bug

There are no recipes for the bucket version

### Reproduction Steps

N/A

### Expected Result

For bucket of the spawn fluid to have a recipethe 

### Operating System

Windows 11

### Mod Version

0.0.14.e-22

### Minecraft Version

1.20.1

### Forge Version

47.3.5

**Comment by oierbravo** [comment]
Fixed!
Thanks!
