### ISSUE TITLE
[1.20.1] Ghast are not spawning 

### ISSUE THREAD

**Issue by Ligmaphobia** [oierbravo/create-mechanical-spawner#18]
### Describe the Bug

Putting ghast spawn fluid into the spawner doesn't spawn the ghast and doesn't use any ghast spawn fluid when spawn progress reaches 100%
It seems that other mobs spawn fine.

It looks like the ghast spawn recipe uses the wrong fluid (It uses enderman fluid instead of ghast fluid)

[1.20.1], didn't test other versions

### Reproduction Steps

1.Place down a mechanical spawner
2.Give it rotational power
3.Feed it ghast spawn fluid using a mechanical pump

### Expected Result

A ghast spawns above the mechanical spawner and uses up 100mB of ghast spawn fluid

### Operating System

Windows 10

### Mod Version

0.0.9.c-36

### Minecraft Version

1.19.2

### Forge Version

47.3.0

### Other Mods

The is no crash, I was using a total of 80 mods (create, JEI, embeddium, etc.), none of them seem to be the problem

**Comment by oierbravo** [comment]
Fixed.
Thanks!
