### ISSUE TITLE
Mod not compatible with Multiplayer Server

### ISSUE THREAD

**Issue by SugarDaddii** [oierbravo/create-mechanical-spawner#3]
When i have this mod installed i get a Error Client Side everytime i want to join a Server
![javaw_QmA8g5SUha](https://user-images.githubusercontent.com/14795020/218904790-5ec3a8b2-0a65-4609-b5b1-ff132676e79a.png)
![javaw_XB3iJH4Iu4](https://user-images.githubusercontent.com/14795020/218904802-ef5e0f93-126d-4cbb-922b-e7d59e54abfd.png)
![javaw_20vJBqeaeQ](https://user-images.githubusercontent.com/14795020/218904814-d2adc2fe-a0ae-4f9a-8526-852d2f7f541e.png)

and its everytime another eroor but when i delete it all is fine again

**Comment by genesy** [comment]
@oierbravo still in development?

**Comment by Danymaddox** [comment]
I do have the same problem here, any updates? <3

**Comment by Ryvexam** [comment]
Confirmed, work without this mod

**Comment by oierbravo** [comment]
Hi all!
Thanks for the reports.
I'm havin troubles fixing and debuging the error, but I think it may be ok now.
Already uploaded a new version to curseforge.
