### ISSUE TITLE
Create 0.5.1.a is incompatible

### ISSUE THREAD

**Issue by LandofHeros2234** [oierbravo/create-mechanical-spawner#4]

**Comment by raimkras97** [comment]
[18Jul2023 09:32:44.597] [main/ERROR] [net.minecraftforge.fml.loading.ModSorter/LOADING]: Missing or unsupported mandatory dependencies:
	Mod ID: 'create', Requested by: 'create_mechanical_spawner', Expected range: '[0.5.0.i,0.5.1)', Actual version: '0.5.1.c'

**Comment by BraveCaperCat2** [comment]
Same issue but minecraft loads and says that the mod requires a version of create above 0.5.0i, but below 0.5.1

**Comment by oierbravo** [comment]
Updated.
