### ISSUE TITLE
Crash when creating world

### ISSUE THREAD

**Issue by Tecohg** [oierbravo/create-mechanical-spawner#5]
I have added Create mechanical spawners to a heavy modpack im making, and i've been getting a crash when trying to create or join a world, (yes im sure the crash is coming from this mod, i have tested with and without it, only crashes when it is added.
Heres the latest log:
[latest.log](https://github.com/oierbravo/create-mechanical-spawner/files/12207820/latest.log)

**Comment by oierbravo** [comment]
hi! working on it!

**Comment by oierbravo** [comment]
Just uploaded a new version
